-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 18:30:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisTerminal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisTerminal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisTerminal` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sisTerminal` ;

-- -----------------------------------------------------
-- Table `sisTerminal`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisTerminal`.`bus` (
  `id_bus` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NOT NULL,
  `tipoBus` VARCHAR(45) NOT NULL DEFAULT 'Normal',
  `plazas` INT NOT NULL DEFAULT 1,
  `estado` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_bus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisTerminal`.`destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisTerminal`.`destinos` (
  `id_destino` INT NOT NULL AUTO_INCREMENT,
  `nombre_destino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_destino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisTerminal`.`conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisTerminal`.`conductor` (
  `id_conductor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `salario` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_conductor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisTerminal`.`Viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisTerminal`.`Viaje` (
  `idViaje` INT NOT NULL AUTO_INCREMENT,
  `id_bus` INT NOT NULL,
  `id_conductor` INT NOT NULL,
  `id_destino` INT NOT NULL,
  `fecha_viaje` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`idViaje`),
  INDEX `fk_bus_Viaje_idx` (`id_bus` ASC),
  INDEX `fk_conductor__idx` (`id_conductor` ASC),
  INDEX `fk_destino_viaje_idx` (`id_destino` ASC),
  CONSTRAINT `fk_bus_Viaje`
    FOREIGN KEY (`id_bus`)
    REFERENCES `sisTerminal`.`bus` (`id_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conductor_viaje`
    FOREIGN KEY (`id_conductor`)
    REFERENCES `sisTerminal`.`conductor` (`id_conductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destino_viaje`
    FOREIGN KEY (`id_destino`)
    REFERENCES `sisTerminal`.`destinos` (`id_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
